# Generated by Django 4.2.13 on 2024-07-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("hire_date", models.DateField()),
                ("job_id", models.CharField(max_length=10)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_pct",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("manager_id", models.IntegerField()),
                ("department_id", models.IntegerField()),
            ],
        ),
    ]
